#!/bin/bash
echo "Running pre-push hook..."

# Run tests before pushing
./vendor/bin/phpunit

# Trigger a Packagist update (optional)
curl -XPOST https://packagist.org/api/update-package?username=rasulsafarovitch&apiToken=d768944145245ff5ab75 -d '{"repository":{"url":"https://github.com/safarovitch/alif-capital-equiring"}}'

echo "Pre-push hook completed."
